version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: goodbuying-mysql
    environment:
      MYSQL_ROOT_PASSWORD: hello
      MYSQL_DATABASE: goodbuying
      MYSQL_USER: hello
      MYSQL_PASSWORD: hello
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
