name: Deploy to Development Server

on:
  push:
    branches: [ devel ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build -x test
      
    - name: List JAR files
      run: ls -la build/libs/
      
    - name: Build Docker image
      run: |
        docker build -t goodbuying-api-server:latest .
        docker save goodbuying-api-server:latest | gzip > goodbuying-api-server.tar.gz
        
    - name: Copy files to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 9952
        timeout: 60s
        command_timeout: 30m
        source: "goodbuying-api-server.tar.gz,deploy.sh"
        target: "/home/${{ secrets.SERVER_USER }}/goodbuying-api"
        debug: true
        
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 9952
        timeout: 60s
        command_timeout: 30m
        debug: true
        script: |
          cd /home/${{ secrets.SERVER_USER }}/goodbuying-api
          chmod +x deploy.sh
          ./deploy.sh